// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RunGitStatus(arg1) {
  return window['go']['main']['App']['RunGitStatus'](arg1);
}
