// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CommitGitChanges(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function PickFolder():Promise<string>;

export function PullGitChanges():Promise<void>;

export function PushGitChanges():Promise<void>;

export function RunGitStatus(arg1:string):Promise<main.GitStatusResult>;

export function StageGitFile(arg1:string):Promise<void>;

export function SwitchGitBranch(arg1:string):Promise<void>;

export function UnstageGitFile(arg1:string):Promise<void>;
