// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';

export function AbortMerge():Promise<void>;

export function CommitGitChanges(arg1:string):Promise<void>;

export function ContinueMerge():Promise<void>;

export function DeleteGitBranch(arg1:string,arg2:boolean):Promise<void>;

export function DiscardGitFile(arg1:string):Promise<string>;

export function GetCommitHistory():Promise<any>;

export function GetGitBranches():Promise<any>;

export function GitDiff():Promise<git.GitDiffResult>;

export function GitDiffStaged():Promise<git.GitDiffResult>;

export function GitFetch():Promise<string>;

export function GitPrune():Promise<string>;

export function PickFolder():Promise<string>;

export function PullGitChanges():Promise<void>;

export function PushGitChanges():Promise<void>;

export function ResolveGitConflict(arg1:string,arg2:string):Promise<void>;

export function RunGitStatus():Promise<git.GitStatusResult>;

export function SetRepositoryPath(arg1:string):Promise<void>;

export function StageGitFile(arg1:string):Promise<string>;

export function SwitchGitBranch(arg1:string):Promise<void>;

export function UnstageGitFile(arg1:string):Promise<string>;
