// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitGitChanges(arg1) {
  return window['go']['main']['App']['CommitGitChanges'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PullGitChanges() {
  return window['go']['main']['App']['PullGitChanges']();
}

export function PushGitChanges() {
  return window['go']['main']['App']['PushGitChanges']();
}

export function RunGitStatus(arg1) {
  return window['go']['main']['App']['RunGitStatus'](arg1);
}

export function StageGitFile(arg1) {
  return window['go']['main']['App']['StageGitFile'](arg1);
}

export function UnstageGitFile(arg1) {
  return window['go']['main']['App']['UnstageGitFile'](arg1);
}
