// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function PickFolder():Promise<string>;

export function RunGitStatus(arg1:string):Promise<string>;
